### ISSUE TITLE
request support for marlin

### ISSUE THREAD

**Issue by jon012198** [xyzaxyz/OctoPrint-Finetunerptr#1]
can it work for marlin too

**Comment by xyzaxyz** [comment]
Hey, sadly I don't know about marlin's eeprom loading/saving communications and don't use a marlin based printer myself. 
Currently it's not possible for me, sorry. By time I may come back to this topic, or another github user can make their commits to the project :)

**Comment by ZhenyaKa** [comment]
I want marlin fucionality too!
