### ISSUE TITLE
i have rostock max2 and this does not work 

### ISSUE THREAD

**Issue by gurusonwheels** [xyzaxyz/OctoPrint-Finetunerptr#5]
on rostock max 2 that is repeater based .
i get a connect button 
when i connect i get a orange yelllow light 
that says eeprom ready to read . 

but there is no way to read anything . 

i notice in the terminal that the printer keeps being reset  .

**Comment by xyzaxyz** [comment]
Hi,

as your terminal tells you that the printer keeps resetting, I can't really relate that issue with the plugin.
To me it seems like your octoprint-instance and the rostock have connection / communication problems.
