### ISSUE TITLE
Menu not deploying

### ISSUE THREAD

**Issue by ignaworn** [xyzaxyz/OctoPrint-Finetunerptr#6]
Hi, 
Somewhere after OctoPrint's commit 3799099 (devel branch) the icon in the top-nav bar doesn't open the finetunerptr menu. (I jumped from 3799099 to ad246de, and unfortunately there are lots of commits in between).

The mouse icon doesn't change as if it were a link, see pic below 
![image](https://user-images.githubusercontent.com/6243125/33225861-6c117170-d15e-11e7-8e8c-9bb215641058.png)

When it worked, it showed the link mouse pointer. As seen in this other pic.
![image](https://user-images.githubusercontent.com/6243125/33225868-96b9389a-d15e-11e7-88c2-6b0d046a34fb.png)

Thanks

**Comment by xyzaxyz** [comment]
Hi, 
I tried to reconstruct that error, but sadly for this moment it seems a little more complicated for me than it seemed. Had to upgrade some python dependencies on my windows development environment, but as I want to instantiate octoprint on the dev-branch, I get errors from python about the "psutil" module having no member "cpu_freq()" - which seems to be a problem with my windows environment.

On the latest master branch, I experienced mixed things.
My running "productive" RasPi where a printer is permanently connected is running OctoPrint 1.3.5 (master branch) - the menu deploys as usual, yet the cursor is exactly as you described.

Digging the cursor issue, I found out that the "Settings" get this cursor implicitly by some browser-delivered CSS / webkit:
`a:-webkit-any-link {
    color: -webkit-link;
    cursor: auto;
    text-decoration: underline;
}`

As this somehow doesn't get appended on my link (anymore?) I could fix that by adding the "cursor:pointer" attribute to my link-element.

Well, on my windows "dev env", on the master branch the menu also deployed fine - only there is now a new bug in the view, which also would not appear on any of my live machines.
Can you check, if you experience the same bug in the view, marked in the following picture?
![cg0g0fg](https://user-images.githubusercontent.com/27498403/33228026-b8eb45d6-d1b1-11e7-813d-5500c35261ab.png)

For the beginning, I would advise to switch back to the master branch, depending on your real need for the new, experimental features in octoprint.
If it has a real high priority and is not related to maybe new bugs from the dev branch, I can setup a linux dev env soon and look further into it.

**Comment by ignaworn** [comment]
Hi, 
Sorry for the bad issue reporting, I have no idea what information may be useful to you so if you need me to do something and debug I'll gladly help. Also, I'm aware that dev may have issues, so, no rush. 

I've compared the html tags and the only difference with my version  is that the cursor: pointer tag is not set, but that wont be the responsible for the menu not showing up.
![image](https://user-images.githubusercontent.com/6243125/33242426-a576718a-d2b3-11e7-9801-72ff27a063be.png)

However, I did find this in Chrome's console. I don't know if it's relevant but its more relateable than the cursor.
![image](https://user-images.githubusercontent.com/6243125/33242465-3b7509da-d2b4-11e7-91e2-cb288689fc8b.png)

If you need me to do some testing, as I said before, I'll gladly help!

Regards

**Comment by ignaworn** [comment]
Hi, after latest OctoPrint devel commit (48fceac), finetunerptr works again.
My guess is that https://github.com/foosel/OctoPrint/commit/d174d7ab8094b49afd660689a274349043747eb6 is related.

**Comment by xyzaxyz** [comment]
Thanks for reporting back!

**Comment by ignaworn** [comment]
One last update in the topic to help others having the same issue.
Latest OctoPrint devel has a new feature to toggle Plugin Compatibility with JS
![image](https://user-images.githubusercontent.com/6243125/34076298-095520e0-e2c0-11e7-8333-25ab8a75067e.png)
FineTunerPtr needs this option to be checked in order to work. 

Thanks !

**Comment by xyzaxyz** [comment]
Thanks again for reporting that - I recently updated the plugin to a new version which i have tested on my productive units.
I can't relate to specific commits, but both were running the master branch version of octoprint in 1.3.5 and 1.3.6.
The checkbox in the settings menu for legacy plugins doesn't need to get enabled for this plugin anymore (as far as I could test) :)
