### ISSUE TITLE
Should be "disabled" if not logged in

### ISSUE THREAD

**Issue by Tjololo12** [xyzaxyz/OctoPrint-Finetunerptr#7]
I noticed this when I popped onto octoprint from work today. I wasn't logged in, but I could still interact with the plugin https://i.imgur.com/vIl9Ns1.png

I'm not sure if the buttons do anything, because I don't want to mess up the print by hitting them, but IMO the dropdown should either not be there or should be "disabled" like the other inputs from other plugins when you're logged out.

**Comment by xyzaxyz** [comment]
Hi,  
the authentication check has been added with today's update :)  
https://github.com/xyzaxyz/OctoPrint-Finetunerptr/releases/tag/1.3.6.2
